[package]
name = "adaptive-radix-tree"
version = "0.1.0"
authors = ["Gellért Peresztegi-Nagy <gperesztegi@skawa.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
